=== weblips/m1m2-migration-tool/src/Migration/etc/salmon-config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="salmon_config" type="salmonConfigType" />

    <xs:complexType name="salmonConfigType">
        <xs:sequence>
            <xs:element name="source" type="sourceRulesType" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sourceRulesType">
        <xs:sequence>
            <xs:element name="document_rules" type="sourceDocumentRulesType" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="field_rules" type="sourceFieldRulesType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sourceDocumentRulesType">
        <xs:sequence>
            <xs:element name="clean_orphans" type="cleanDocumentOrphansType" maxOccurs="1" minOccurs="0"/>
            <xs:element name="export" type="exportDocumentType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cleanDocumentOrphansType">
        <xs:sequence>
            <xs:element name="document" type="notEmptyString" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="exportDocumentType">
        <xs:sequence>
            <xs:element name="document" type="notEmptyString" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sourceFieldRulesType">
        <xs:sequence>
            <xs:element name="export" type="exportFieldType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="exportFieldType">
        <xs:sequence>
            <xs:element name="field" type="fieldFormatType"/>
            <xs:element name="to" type="fieldFormatType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="fieldFormatType">
        <xs:annotation>
            <xs:documentation>Field format: "document_name.field_name"</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[^.]+\.[^.]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="notEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== weblips/m1m2-migration-tool/src/Migration/config/ee-to-ee/salmon-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<salmon_config xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
               xs:noNamespaceSchemaLocation="../../etc/salmon-config.xsd">
    <source>
        <document_rules>
            <clean_orphans>
                <document>catalog_eav_attribute</document>
                <document>catalog_product_entity_int</document>
                <document>catalog_product_entity_varchar</document>
                <document>customer_eav_attribute</document>
                <document>customer_entity_int</document>
                <document>eav_attribute_group</document>
                <document>eav_attribute_option</document>
                <document>eav_attribute_option_value</document>
                <document>eav_entity_attribute</document>

                <document>core_layout_link</document>
                <document>customer_address_entity_varchar</document>
                <document>customer_form_attribute</document>
                <document>dataflow_profile_history</document>
                <document>widget_instance_page</document>
                <document>widget_instance_page_layout</document>
            </clean_orphans>
        </document_rules>
        <field_rules>
            <export>
                <field>catalog_eav_attribute.can_configure_inheritance</field>
                <to>catalog_eav_attribute.can_configure_inheritance</to>
            </export>
            <export>
                <field>catalog_eav_attribute.inheritance</field>
                <to>catalog_eav_attribute.inheritance</to>
            </export>
            <export>
                <field>catalog_eav_attribute.can_configure_import</field>
                <to>catalog_eav_attribute.can_configure_import</to>
            </export>
            <export>
                <field>catalog_eav_attribute.import_to_dfw</field>
                <to>catalog_eav_attribute.import_to_dfw</to>
            </export>
        </field_rules>
    </source>
</salmon_config>
